#!/bin/sh

mkdir -p opk
cp ./test opk/test
cp ./yes.bmp opk/yes.bmp
cp ./yes2.bmp opk/yes2.bmp
cp ./icon.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Test Rotate
Comment=Test Rotate
Exec=test
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk test_rotate_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
